src/AppBundle/Entity/Galeria.php
<?php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="galeria")
 * @ORM\Entity(repositoryClass="AppBundle\Entity\Repository\GaleriaRepository")
 */
class Galeria {
	/**
	 * @ORM\Column(type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;
	
	/**
	 * @ORM\Column(type="string", length=255, nullable=false)
	 */
	private $nombre;
	
	/**
	 * @ORM\Column(type="array", nullable=true)
	 */
	protected $galeria;
	
	

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     *
     * @return Galeria
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set galeria
     *
     * @param array $galeria
     *
     * @return Galeria
     */
    public function setGaleria($galeria)
    {
    	$galeriaFinal = array();
    	foreach($galeria as $gal) {
    		if(empty($gal)) continue;
    		$galeriaFinal[] = $gal;
    	}
        $this->galeria = $galeriaFinal;

        return $this;
    }

    /**
     * Get galeria
     *
     * @return array
     */
    public function getGaleria()
    {
        return $this->galeria;
    }
    
    
    public function getUploadRootDir()
    {
    	// absolute path to your directory where images must be saved
    	return __DIR__.'/../../../../../public_html/'.$this->getUploadDir();
    }
    
    public function getUploadDir()
    {
    	return 'uploads/galerias';
    }
    
    public function getAbsolutePath()
    {
    	return null === $this->image ? null : $this->getUploadRootDir().'/'.$this->image;
    }
    
    public function getWebPath()
    {
    	return null === $this->image ? null : '/'.$this->getUploadDir().'/'.$this->image;
    }
    
}

src/AppBundle/Resources/views/Sitio/amigos.html.twig
{% extends "AppBundle::Sitio/layout.html.twig" %}

{% block slider_top %}
{% endblock %}

{% block content %}

	<section class="gallery" id="gallery">
		<div class="container">
			<h2>Nuestros amigos</h2>
			{{ render(controller('AppBundle:Default:galeria',{galeria_id: 4})) }}
		</div>
	</section>


{% endblock %}

src/AppBundle/Resources/views/Sitio/cabanas.html.twig
{% extends "AppBundle::Sitio/layout.html.twig" %}

{% block content %}

	<section class="info" id="info">
		<div class="container">
			<h2>Nuestras casas</h2>
			<p><b>Pasajeros:</b> Hasta 5 personas</p>
			<p><b>Superficie:</b> 62m2</p>
			<h3>Equipamiento planta baja</h3>
			<ul class="int">
				<li><span>&check;</span>Cocina con horno tradicional</li>
				<li><span>&check;</span>Heladera con freezer</li>
				<li><span>&check;</span>Microondas</li>
				<li><span>&check;</span>Cafetera eléctrica</li>
				<li><span>&check;</span>Vajilla completa</li>
				<li><span>&check;</span>Sillón cama 1 plaza</li>
				<li><span>&check;</span>TV 21''</li>
				<li><span>&check;</span>DVD</li>
				<li><span>&check;</span>Conexión wi-fi</li>
				<li><span>&check;</span>Baño amplio con ducha y secador de pelo</li>
				<li><span>&check;</span>Calefactor tiro balanceado</li>
				<li><span>&check;</span>Parrilla y espacio exterior individual</li>
				<li><span>&check;</span>Espacio para estacionar</li>
				<li><span>&check;</span>Ducha exterior con agua caliente</li>

			</ul>
			<h3>Equipamiento planta alta</h3>
			<ul>
				<li><span>&check;</span>1 dormitorio matrimonial con amplios placares y cortinas black out</li>
				<li><span>&check;</span>TV LCD 24''</li>
				<li><span>&check;</span>Ventilador de techo</li>
				<li><span>&check;</span>Puerta protectora para chicos en parte superior de la escalera</li>
				<li><span>&check;</span>1 dormitoriocon 2 camas simples de 1 plaza, amplios placares y cortinas black out</li>
				<li><span>&check;</span>Calefactor tiro balanceado en cada dormitorio</li>
				<li><span>&check;</span>Baño principal con hidromasaje y secador de pelo</li>
			</ul>
		</div>
	</section>

	<section class="gallery" id="gallery">
		<div class="container">
			<h2>Galería de fotos</h2>
			{{ render(controller('AppBundle:Default:galeria',{galeria_id: 2})) }}
		</div>
	</section>

{% endblock %}

src/AppBundle/Resources/views/Sitio/component_galeria.html.twig
{% if galeria.id == 1 %}
    {% for gal in galeria.galeria %}
        <div class="item">
            <img src="{{ asset('/uploads/galerias/gallery/') }}{{ gal }}" />
        </div>
	{% endfor %}
{% else %}
<div class="my-gallery" itemscope itemtype="http://schema.org/ImageGallery">
	<div class="row">
		{% set primero = true %}
		{% for gal in galeria.galeria %}
		<figure class="col-sm-3 {% if primero %}mobile-thumb{% endif %}" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
			<a href="{{ asset('/uploads/galerias/gallery/') }}{{ gal }}" itemprop="contentUrl" data-size="800x536">
				<img src="{{ asset('/uploads/galerias/') }}{{ gal|gallery_thumb(350,235) }}" itemprop="thumbnail" alt="Image description" />
				{% if primero %}
					{% set primero = false %}
					<span class="mobile-label">Ver galer&iacute;a</span>
				{% endif %}
			</a>
		</figure>
		{% endfor %}
	</div>
</div>
{% endif %}

src/AppBundle/Resources/views/Sitio/component_promociones.html.twig
	<section class="banners">
		<div class="container">
			<div class="row">
				{% for promocion in promociones %}
				<div class="col-sm-4">
					<div class="item">
						<h2>{{ promocion.nombre }}</h2>
						<img src="{{ promocion.webPath }}" alt="">
						<p>{{ promocion.descripcion|nl2br }}</p>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</section>

{#

	<section class="info">
		<div class="container">
			<div class="row">
			{% for promocion in promociones %}
				<div class="col-sm-4">
					<div class="info-item">
						<img src="{{ promocion.webPath|thumb(355,200) }}" alt="">
						<h3>{{ promocion.nombre }}</h3>
						<p>{{ promocion.descripcion|nl2br }}</p>
					</div>
				</div>
			{% endfor %}
			</div>
		</div>
	</section>

#}

src/AppBundle/Resources/views/Sitio/email_contacto.html.twig
			<strong>Nombre</strong>: {{ nombre }} <br />
			<strong>Mail</strong>: {{ email }} <br />
			<strong>Tel&eacute;fono</strong>: {{ telefono }} <br /> 
			<strong>Mensaje</strong>:<br />
			<p>{{ mensaje|nl2br }}</p>
			

src/AppBundle/Resources/views/Sitio/home.html.twig
{% extends "AppBundle::Sitio/layout.html.twig" %}


    {% block content %}
    
    {{ render(controller('AppBundle:Default:promociones')) }}
	
	<section class="ficha" id="ficha">
		<div class="container">
		    <h2>El Complejo</h2>
			<div class="row">
			    <div class="col-lg-6">
			        <div class="ficha-carousel owl-carousel owl-theme">
			            {{ render(controller('AppBundle:Default:galeria',{galeria_id: 1})) }}
			        </div>
			    </div>
			    <div class="col-lg-6">
			        <p>Casas a 80 mts del mar, con todo el confort y el equipamiento para que tengas la mejor estadía.</p>
			        <p>Contamos con 2 Casas de 62 m2 cada una, con espacios amplios y muy cómodos.<br>Porque ya conoces nuestra atención personalizada y ahora te ofrecemos esta nueva propuesta, ideal para disfrutar con amigos y en familia.</p>
			        <p>Te esperamos!</p>
			        <p>Celina y Lucio.</p>
			        <p>Equipamiento:</p>
			        <ul class="main-list">
                        <li><i class="fas fa-check-circle"></i>Nuestra atención personalizada</li>
                        <li><i class="fas fa-check-circle"></i>Desayuno completo</li>
                        <li><i class="fas fa-check-circle"></i>Limpieza</li>
                        <li><i class="fas fa-check-circle"></i>Ropa de blanco</li>
                        <li><i class="fas fa-check-circle"></i>Lavado de vajilla (sólo una vez al día)</li>
                        <li><i class="fas fa-check-circle"></i>Sombrillas y reposeras para la playa (solo en temporada alta)</li>
                        <li><i class="fas fa-check-circle"></i>Conexión wi-fi libre en ambas Casas</li>
                        <li><i class="fas fa-check-circle"></i>TV LCD</li>
                        <li><i class="fas fa-check-circle"></i>DVD</li>
                        <li><i class="fas fa-check-circle"></i>Calefacción en todos los ambientes</li>
                        <li><i class="fas fa-check-circle"></i>Ventilador de techo</li>
                        <li><i class="fas fa-check-circle"></i>Cuna y sillita para babé</li>
                        <li><i class="fas fa-check-circle"></i>Parrillas individuales</li>
                        <li><i class="fas fa-check-circle"></i>Secador de cabelli</li>
                        <li><i class="fas fa-check-circle"></i>Heladera con freezer y cocina con horno</li>
                        <li><i class="fas fa-check-circle"></i>Microondas</li>
                        <li><i class="fas fa-check-circle"></i>Vajilla completa</li>
                        <li><i class="fas fa-check-circle"></i>Cafetera eléctrica</li>
                        <li><i class="fas fa-check-circle"></i>Estacionamiento</li>
                        <li><i class="fas fa-check-circle"></i>Horno de barro (siempre te sorprendemos con algo rico)</li>
        			</ul>
			    </div>
			</div>
		</div>
	</section>

	<section class="map" id="ubicacion">
		<div class="container">
			<h2>Ubicación</h2>
		</div>
		<div id="map-container" class="z-depth-1" style="height: 500px"></div>
	</section>

	<section class="contact" id="contact">
		<div class="container">
			<h2>Contacto</h2>
			<form  id="form_contacto" method="post" onsubmit="return validar_form();">
				<div class="row">
					<div class="col-sm-6">
						<input type="text" placeholder="Nombre" required="required" id="form_nombre">
						<input type="email" placeholder="Mail" required="required" id="form_email">
						<input type="text" placeholder="Teléfono" required="required" id="form_telefono">
					</div>
					<div class="col-sm-6">
						<textarea placeholder="Comentario" id="form_mensaje"></textarea>
					</div>
					<div class="col-sm-12">
						<a href="" class="send">Enviar</a>
					</div>
				</div>
			</form>
		</div>
	</section>
{% endblock %}	

src/AppBundle/Resources/views/Sitio/layout.html.twig
<!DOCTYPE html>

<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="Nombre" content="Caba&ntilde;as Pi-Hue | Las Gaviotas" />
	<meta name="DC.Title" content="Caba&ntilde;as en las Gaviotas | Caba&ntilde;as Pi-Hue | Alojamiento en Las Gaviotas" />
	<meta http-equiv="title" content="Caba&ntilde;as en las Gaviotas | Caba&ntilde;as Pi-Hue | Alojamiento en Las Gaviotas" />
	<meta name="description" content="En Las Gaviotas, a 20 metros del mar, Caba&ntilde;as Pi-Hue, atendido por sus due&ntilde;os. Caba&ntilde;as para 4/5 personas y Suites para 2/3 personas. Parrilas, horno de barro, servicio de playa " />
	<meta name="abstract" content="En Las Gaviotas, a 20 metros del mar, Caba&ntilde;as Pi-Hue, atendido por sus due&ntilde;os. Caba&ntilde;as para 4/5 personas y Suites para 2/3 personas. Parrilas, horno de barro, servicio de playa." />
	<meta name="keywords" content="Las Gaviotas, alojamiento, caba&ntilde;as, cabanas, alquiler, vacaciones, promociones" />
	
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
	<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
	<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png" />
	<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png" />
	<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png" />
	<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png" />
	<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png" />
	<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png" />
	<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png" />
	<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png" />
	
	<meta name="distribution" content="Global" />
	<meta name="identifier-url" content="www.cabaniaspihue.com.ar" />
	<meta name="rating" content="general" />
	<meta name="author" content="www.lasgaviotas.travel" />
	<meta name="reply-to" content="" />
	<meta name="robots" content="all" />
	<meta name="revisit-after" content="7 day" />
	<meta name="DC.Language" scheme="RFC1766" content="Spanish" />

	<meta property="og:url" content="http://www.casaspihue.com.ar" />
	<meta property="og:type" content="article" />
	<meta property="og:title" content="Casas Pihue, A 80 metros del mar" />
	<meta property="og:description" content="En Las Gaviotas, a 80 metros del mar, Casas Pi-Hue, atendido por sus due&ntilde;os. Casas para 4/5 personas." />
	<meta property="og:image" content="http://www.casaspihue.com.ar/bundles/app/images/layout/og-06.jpg" />

<meta name="google-site-verification" content="-mvD0fvzOYjmJpP29vN7f9bXtwWKkEFo92Ed_S1Dw8Y" />
	<!-- CSS -->
	<link href="{{ asset('bundles/app/stylesheets/screen.css') }}" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="{{ asset('bundles/app/stylesheets/fonts.css') }}" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="{{ asset('bundles/app/stylesheets/fonts-site.css') }}" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="{{ asset('bundles/app/stylesheets/photoswipe.css') }}" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="{{ asset('bundles/app/stylesheets/default-skin.css') }}" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="{{ asset('bundles/app/stylesheets/owl.carousel.css') }}" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="{{ asset('bundles/app/stylesheets/owl.transitions.css') }}" media="screen, projection" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
	<!-- FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
	<!-- JS -->
	<script type="text/javascript" src="{{ asset('bundles/app/js/jquery-2.2.3.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('bundles/app/js/functions.js') }}"></script>
	<script type="text/javascript" src="{{ asset('bundles/app/js/photoswipe.js') }}"></script>
	<script type="text/javascript" src="{{ asset('bundles/app/js/photoswipe-ui.js') }}"></script>
	<script type="text/javascript" src="{{ asset('bundles/app/js/owl.carousel.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('bundles/app/js/scroll.js') }}"></script>
	<script type="text/javascript" src="{{ asset('bundles/app/js/contacto.js') }}"></script>
	
	<script src="https://maps.google.com/maps/api/js?key=AIzaSyCaJw8REV5CNiAQbirsgFxKonBLjAankBM"></script> 
    <!-- <script src="https://maps.google.com/maps/api/js"></script>-->
    <script type="text/javascript">
        //GOOGLE MAP
        function regular_map() {
        var var_location = new google.maps.LatLng(-37.340859, -57.027926);

        var var_mapoptions = {
        center: var_location,
        zoom: 16,
        streetViewControl: true,
        mapTypeId: google.maps.MapTypeId.SATELLITE
        };

        var var_map = new google.maps.Map(document.getElementById("map-container"),
        var_mapoptions);

        var var_marker = new google.maps.Marker({
        position: var_location,
        map: var_map,
        title: "CABAÑAS PIHUE - LAS-GAVIOTAS"
        });
        }

        // Initialize maps
        google.maps.event.addDomListener(window, 'load', regular_map);
    </script>




<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-43021299-1', 'cabaniaspihue.com.ar');
  ga('send', 'pageview');
</script>


</head>

<body class="loading">

	

	<section class="intro" id="intro">
		{% block slider_top %}
		<div class="slider">
			<img src="{{ asset('bundles/app/images/slider/001.jpg') }}" alt="">
			<img src="{{ asset('bundles/app/images/slider/002.jpg') }}" alt="">
		</div>
		{% endblock %}
		<div class="sub-header">
			<div class="container">
				<ul class="social">
					<li><a href="https://www.facebook.com/casaspihue/" target="_blank"><i class="fab fa-facebook-f"></i></li></a>
					<!--<li><a href=""><span class="icon-site-twitter"></span></li></a>
					<li><a href="" target="_blank"><span class="icon-site-google-plus"></span></li></a>-->
					<li><a href="https://www.instagram.com/cabaniaspihue/" target="_blank"><i class="fab fa-instagram"></i></li></a>
					<li><a href="https://wa.me/5492267419940" target="_blank"><i class="fab fa-whatsapp"></i></li></a>
				</ul>
				<ul class="numbers">
					<li><span class="icon-site-cel"></span> (02267) 15 41-9940</li>
					<li><span class="icon-site-tel"></span> (02255) 46-8864</li>
				</ul>
			</div>
		</div>
		<header>
			<div class="container">
				<button class="hamburger hamburger--spin" type="button">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</button>
				<a href="{{ path('homepage') }}"><div class="logo"></div></a>
				<nav>
					<ul>
						<li><a {% if app.request.attributes.get('_route') == 'homepage' %} data-scroll href="#intro"{% else %}href="{{ path('homepage') }}#intro"{% endif %}>Inicio</a></li>
						<li><a href="{{ path('cabanas') }}">Las Casas</a></li>
						
						<li><a {% if app.request.attributes.get('_route') == 'homepage' %} data-scroll href="#ficha"{% else %}href="{{ path('homepage') }}#ficha"{% endif %}>Equipamiento</a></li>
	
						
						<li><a {% if app.request.attributes.get('_route') == 'homepage' %} data-scroll href="#ubicacion"{% else %}href="{{ path('homepage') }}#ubicacion"{% endif %}>Ubicación</a></li>
						<li><a {% if app.request.attributes.get('_route') == 'homepage' %} data-scroll href="#contact"{% else %}href="{{ path('homepage') }}#contact"{% endif %}>Contacto</a></li>
					</ul>
				</nav>
			</div>
		</header>
	</section>

	{% block content %}
	{% endblock %}

	<footer>
		<div class="container">
			<div class="row">
				<div class="col-sm-4">
					<div class="logo"></div>
					<p>Calle 34 entre Mar Azul y playa<br>
					        <strong>Las Gaviotas</strong> / Buenos Aires / Argentina<br>
					        Teléfono: (02255) 46.8864<br>
					        Celular: (02267) 15 41.9940<br>
					        <a href="mailto:consultas@cabaniaspihue.com.ar">consultas@cabaniaspihue.com.ar</a></p>
					        <p>
					        	Visitá también:<br>
								<a href="http://www.cabaniaspihue.com.ar" target="_blank">www.cabaniaspihue.com.ar</a>
					        </p>
				</div>
				<div class="col-sm-8">
					<ul>
						<li><a {% if app.request.attributes.get('_route') == 'homepage' %} data-scroll href="#intro"{% else %}href="{{ path('homepage') }}#intro"{% endif %}>Inicio</a></li>
						<li><a href="{{ path('cabanas') }}">Las Casas</a></li>
						
						<li><a {% if app.request.attributes.get('_route') == 'homepage' %} data-scroll href="#ficha"{% else %}href="{{ path('homepage') }}#ficha"{% endif %}>Equipamiento</a></li>
	
						
						<li><a {% if app.request.attributes.get('_route') == 'homepage' %} data-scroll href="#ubicacion"{% else %}href="{{ path('homepage') }}#ubicacion"{% endif %}>Ubicación</a></li>
						<li><a {% if app.request.attributes.get('_route') == 'homepage' %} data-scroll href="#contact"{% else %}href="{{ path('homepage') }}#contact"{% endif %}>Contacto</a></li>
					</ul>
					<ul class="social">
						<li><a href="https://www.facebook.com/casaspihue/" target="_blank"><i class="fab fa-facebook-f"></i></li></a>
						<!--<li><a href=""><span class="icon-site-twitter"></span></li></a>
						<li><a href="" target="_blank"><span class="icon-site-google-plus"></span></li></a>-->
						<li><a href="https://www.instagram.com/cabaniaspihue/" target="_blank"><i class="fab fa-instagram"></i></li></a>
						<li><a href="https://wa.me/5492267419940" target="_blank"><i class="fab fa-whatsapp"></i></li></a>
					</ul>
					<div id="caja-DATAFISCAL"> <a href="http://qr.afip.gob.ar/?qr=zdOcK00eqIQ03eu-a_9khw,," target="_F960AFIPInfo"><img src="/bundles/app/images/layout/DATAWEB.gif" border="0"></a></div>
				</div>
			</div>
		</div>
	</footer>

	<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="pswp__bg"></div>
		<div class="pswp__scroll-wrap">
			<div class="pswp__container">
				<div class="pswp__item"></div>
				<div class="pswp__item"></div>
				<div class="pswp__item"></div>
			</div>
			<div class="pswp__ui pswp__ui--hidden">
				<div class="pswp__top-bar">
					<div class="pswp__counter"></div>
					<button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
					<button class="pswp__button pswp__button--share" title="Share"></button>
					<button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
					<button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
					<div class="pswp__preloader">
						<div class="pswp__preloader__icn">
							<div class="pswp__preloader__cut">
								<div class="pswp__preloader__donut"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
					<div class="pswp__share-tooltip"></div>
				</div>
				<button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
				<button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
				<div class="pswp__caption">
					<div class="pswp__caption__center"></div>
				</div>
			</div>
		</div>
	</div>

</body>

</html>

src/AppBundle/Resources/views/Sitio/suites.html.twig
{% extends "AppBundle::Sitio/layout.html.twig" %}

{% block content %}

	<section class="info" id="info">
		<div class="container">
			<h2>Suites para 2/3 personas</h2>
			<p><b>Pasajeros:</b> Dos adultos y un niño hasta 2 años</p>
			<p><b>Superficie:</b> 25m2</p>
			<h3>Equipamiento</h3>
			<ul class="int">
				<li><span>&check;</span>Sommier de 2 plazas</li>
				<li><span>&check;</span>Futón de una plaza</li>
				<li><span>&check;</span>Aire acondicionado split frío/calor</li>
				<li><span>&check;</span>TV lCD 32''</li>
				<li><span>&check;</span>DVD</li>
				<li><span>&check;</span>Parrillas en el jardín (una por cada suite)</li>
				<li><span>&check;</span>Balcón individual (planta baja)</li>
				<li><span>&check;</span>Espacio exterior individual (planta baja)</li>
				<li><span>&check;</span>Estacionamiento</li>
				<li><span>&check;</span>Conexión WI-FI</li>
				<li><span>&check;</span>Ventilador de techo</li>
				<li><span>&check;</span>2 paneles calefactores</li>
				<li><span>&check;</span>Baño completo con bañera</li>
				<li><span>&check;</span>Secado de cabello</li>
				<li><span>&check;</span>Cocina con horno tradicional</li>
				<li><span>&check;</span>Heladera</li>
				<li><span>&check;</span>Microondas</li>
				<li><span>&check;</span>Cafetera eléctrica</li>
				<li><span>&check;</span>Exprimidor eléctrico</li>
				<li><span>&check;</span>Tostadora</li>
				<li><span>&check;</span>Vajilla completa</li>
			</ul>
		</div>
	</section>

	<section class="gallery" id="gallery">
		<div class="container">
			<h2>Galería de fotos</h2>
			{{ render(controller('AppBundle:Default:galeria',{galeria_id: 3})) }}
		</div>
	</section>

{% endblock %}